/**
 * Dialect layer (Step 6B): translates the application's SQLite-flavoured SQL
 * into the active database's dialect.
 *
 * Design rules:
 *  - The SQLite dialect is the project's lingua franca: repositories write
 *    SQLite SQL, and on the SQLite path the translator is a no-op so the SQL
 *    reaching node:sqlite is BYTE-IDENTICAL to pre-6B behavior.
 *  - A real engine exists only for PostgreSQL. It is deterministic and unit
 *    tested (tests/adapter.test.ts) but NOT wired to a live database in 6B —
 *    no Supabase tables exist yet (schema apply is a later step).
 *  - Nothing here changes business semantics: translations are syntactic
 *    equivalents of the §6A findings:
 *      INSERT OR IGNORE  -> INSERT ... ON CONFLICT (<key>) DO NOTHING
 *      LIKE ? COLLATE NOCASE -> ILIKE ?
 *      json_extract(col, '$.a.b') -> (col #>> '{a,b}')
 *      strftime('%Y-...','now')   -> now()
 *      length(x)                  -> char_length(x)
 *      INTEGER PRIMARY KEY AUTOINCREMENT -> identity column
 *      BEGIN IMMEDIATE            -> BEGIN
 *  - Unknown INSERT OR IGNORE targets fail fast on PostgreSQL instead of
 *    silently changing duplicate semantics.
 */

export type Dialect = 'sqlite' | 'postgresql';

export function getDialect(): Dialect {
  const raw = (process.env.MATERIALIQ_DB_DIALECT ?? 'sqlite').toLowerCase();
  // 'postgres' and 'postgresql' are accepted aliases; everything else -> sqlite.
  return raw === 'postgres' || raw === 'postgresql' ? 'postgresql' : 'sqlite';
}

export function isPostgres(): boolean {
  return getDialect() === 'postgresql';
}

/**
 * INSERT OR IGNORE call sites with their PG conflict targets. Kept explicit
 * (not inferred) because PostgreSQL requires the concrete key and guessing it
 * from SQL text could silently change duplicate-handling semantics.
 */
const IGNORE_SITES: Array<{ table: RegExp; target: string }> = [
  { table: /INSERT\s+OR\s+IGNORE\s+INTO\s+review_queue\b/i, target: '(match_id)' },
  { table: /INSERT\s+OR\s+IGNORE\s+INTO\s+matching_run_chunks\b/i, target: '(run_id, chunk_index)' },
  { table: /INSERT\s+OR\s+IGNORE\s+INTO\s+import_run_chunks\b/i, target: '(run_id, chunk_index)' },
];

/**
 * Boolean columns are real booleans on PostgreSQL but 0/1 INTEGERs on SQLite.
 * Application SQL is written SQLite-style (`boolcol = 1`), which PostgreSQL
 * rejects (`operator does not exist: boolean = integer`). Translate inline
 * integer literals on the schema's boolean columns only — explicit list, no
 * guessing (Step 8 parity gate finding).
 */
const BOOLEAN_COLUMNS = ['category_compatible', 'is_active', 'is_critical'];

function translateBooleanLiterals(sql: string): string {
  let out = sql;
  for (const col of BOOLEAN_COLUMNS) {
    out = out.replace(new RegExp('\\b' + col + '\\s*=\\s*1\\b', 'gi'), col + ' = true');
    out = out.replace(new RegExp('\\b' + col + '\\s*=\\s*0\\b', 'gi'), col + ' = false');
    out = out.replace(new RegExp('\\b' + col + '\\s*(!=|<>)\\s*1\\b', 'gi'), col + ' <> true');
    out = out.replace(new RegExp('\\b' + col + '\\s*(!=|<>)\\s*0\\b', 'gi'), col + ' <> false');
  }
  return out;
}

/** Translate SQLite-flavoured SQL (identity unless the PostgreSQL dialect is active). */
export function translateSql(sql: string, dialect: Dialect = getDialect()): string {
  if (dialect !== 'postgresql') return sql;

  let out = sql;

  // strftime('%Y-%m-%dT%H:%M:%fZ','now') -> now()  (timestamp DDL + defaults)
  out = out.replace(/strftime\(\s*'(?:[^']|'')*'\s*,\s*'(?:now|localtime)[^']*'\s*\)/gi, 'now()');

  // INTEGER PRIMARY KEY AUTOINCREMENT -> identity (DDL only; repositories
  // never send DDL, kept for completeness so the module can render schema DDL).
  out = out.replace(
    /\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi,
    'integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
  );

  // length( -> char_length(  (same semantics for text on both engines)
  out = out.replace(/\blength\(/gi, 'char_length(');

  // LIKE <param|literal> COLLATE NOCASE -> ILIKE <param|literal>
  out = out.replace(/LIKE\s+(\?|'(?:[^']|'')*')\s+COLLATE\s+NOCASE/gi, 'ILIKE $1');

  // <expr> = ? COLLATE NOCASE -> (lower(expr) = lower(?))   (Step 8 finding)
  // Expression-level NOCASE (e.g. `original_code = ? COLLATE NOCASE`) is not a
  // LIKE, so the ILIKE rule never sees it and PostgreSQL rejects the unknown
  // "nocase" collation. Case-insensitive equality via lower() on both sides
  // is the semantically equivalent comparison (codes are ASCII in this
  // dataset, matching SQLite's ASCII-only NOCASE behavior).
  out = out.replace(
    /\b([A-Za-z_][\w."]*)\s*=\s*\?\s*COLLATE\s*NOCASE\b/gi,
    '(lower($1) = lower(?))'
  );

  // boolean columns: SQLite-style integer literals -> PG booleans
  out = translateBooleanLiterals(out);

  // GROUP_CONCAT(expr)        -> string_agg(expr::text, ',')
  // GROUP_CONCAT(expr, 'sep') -> string_agg(expr::text, 'sep')
  // SQLite's optional-separator aggregate has a PostgreSQL spelling with the
  // same semantics; the ::text cast mirrors SQLite's implicit TEXT affinity.
  out = out.replace(
    /\bGROUP_CONCAT\s*\(\s*((?:[^'()]|'(?:[^']|'')*'|\((?:[^()]|\([^()]*\))*\))*?)\s*(?:,\s*('(?:[^']|'')*')\s*)?\)/gi,
    (_m: string, expr: string, sep?: string) =>
      `string_agg((${expr.trim()})::text, ${sep ?? "','"})`
  );

  // json_extract(col, '$.a.b') -> (col #>> '{a,b}')  — dotted paths only,
  // which covers every production call site.
  out = out.replace(
    /\bjson_extract\s*\(\s*([A-Za-z_][\w."]*(?:\s*\.\s*[A-Za-z_][\w"]*)*)\s*,\s*'(\$[\w.[\]]+)'\s*\)/gi,
    (_m: string, col: string, path: string) => {
      const parts = path
        .replace(/^\$/, '')
        .split(/[.[\]]+/)
        .filter(Boolean);
      return `(${col.trim()}#>>'{${parts.join(',')}}')`;
    }
  );

  // INSERT OR IGNORE: the statement translator resolves known targets below;
  // unknown ones must fail loudly rather than change duplicate semantics.
  return out;
}

/** Translate one statement, including call-site-aware OR IGNORE handling. */
export function translateStatement(sql: string, dialect: Dialect = getDialect()): string {
  const base = translateSql(sql, dialect);
  if (dialect !== 'postgresql') return base;

  const ignoreMatch = /\bINSERT\s+OR\s+IGNORE\s+INTO\s+(\w+)/i.exec(base);
  if (ignoreMatch) {
    for (const site of IGNORE_SITES) {
      if (site.table.test(base)) {
        return base.replace(/\bINSERT\s+OR\s+IGNORE\s+INTO/i, 'INSERT INTO') + ` ON CONFLICT ${site.target} DO NOTHING`;
      }
    }
    throw new Error(
      `PG dialect: INSERT OR IGNORE into "${ignoreMatch[1]}" has no registered conflict target — refusing to translate (duplicate semantics would change).`
    );
  }
  return base;
}
