-- ============================================================================
-- MaterialIQ — PostgreSQL/Supabase schema (DRAFT — NOT APPLIED in Step 6A)
-- ============================================================================
-- Source of truth: SQLite `data/materialiq.db` at migration version 11
-- ("import-jobs"), dumped live from sqlite_master on 2026-09-20.
--
-- Translation rules applied (see supabase/README.md for the full mapping):
--   * INTEGER PRIMARY KEY AUTOINCREMENT -> bigint GENERATED BY DEFAULT AS IDENTITY
--     (BY DEFAULT, not ALWAYS, so the Step-6C data load can supply SQLite ids)
--   * REAL                              -> double precision
--   * TEXT timestamps (ISO-8601 'Z')    -> timestamptz (semantically equivalent)
--   * INTEGER 0/1 booleans              -> boolean (the 0/1 CHECK becomes
--     structurally impossible; no constraint weakened)
--   * strftime('%Y-%m-%dT%H:%M:%fZ','now') -> now()
--   * length(x)                         -> char_length(x)
--   * Partial unique index ON ((1)) WHERE ... kept verbatim (valid PG idiom)
--   * evidence TEXT stays JSON-capable: promoted to jsonb because production SQL
--     already queries it by path (json_extract, 6 call sites). All other JSON-
--     looking TEXT columns stay text (app code serializes/deserializes them
--     whole; see supabase/README.md § JSON decisions).
--   * Index names are preserved 1:1 for traceability.
--   * No triggers exist in SQLite v11; none are created here.
--   * No extensions are required (no pgvector, no citext).
--
-- Scope: public schema ONLY. Does not touch auth/storage/Supabase-managed
-- schemas. Deterministic single-apply migration (Supabase runner tracks it in
-- supabase_migrations.schema_migrations; the app-owned _migrations table below
-- is the application-level registry, mirroring SQLite).
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Domain core
-- ---------------------------------------------------------------------------

CREATE TABLE organizations (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          code text NOT NULL UNIQUE CHECK (char_length(code) BETWEEN 2 AND 10),
          name text NOT NULL CHECK (char_length(name) BETWEEN 2 AND 120),
          description text,
          status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

CREATE TABLE data_imports (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          organization_id bigint NOT NULL REFERENCES organizations(id),
          file_name text NOT NULL,
          file_type text NOT NULL CHECK (file_type IN ('csv','xlsx')),
          total_rows integer NOT NULL DEFAULT 0 CHECK (total_rows >= 0),
          successful_rows integer NOT NULL DEFAULT 0 CHECK (successful_rows >= 0),
          failed_rows integer NOT NULL DEFAULT 0 CHECK (failed_rows >= 0),
          status text NOT NULL DEFAULT 'pending'
            CHECK (status IN ('pending','processing','completed','failed')),
          error_info text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          new_rows integer NOT NULL DEFAULT 0 CHECK (new_rows >= 0),
          duplicate_rows integer NOT NULL DEFAULT 0 CHECK (duplicate_rows >= 0),
          warning_rows integer NOT NULL DEFAULT 0 CHECK (warning_rows >= 0),
          missing_description_rows integer NOT NULL DEFAULT 0 CHECK (missing_description_rows >= 0),
          workflow_status text NOT NULL DEFAULT 'completed'
            CHECK (workflow_status IN ('uploaded','validating','ready','importing','completed','completed_with_warnings','failed')),
          valid_rows integer NOT NULL DEFAULT 0 CHECK (valid_rows >= 0),
          error_rows integer NOT NULL DEFAULT 0 CHECK (error_rows >= 0),
          empty_rows integer NOT NULL DEFAULT 0 CHECK (empty_rows >= 0),
          imported_rows integer NOT NULL DEFAULT 0 CHECK (imported_rows >= 0),
          skipped_existing_rows integer NOT NULL DEFAULT 0 CHECK (skipped_existing_rows >= 0),
          updated_rows integer NOT NULL DEFAULT 0 CHECK (updated_rows >= 0),
          column_mapping text,
          row_report text,
          duplicate_strategy text
            CHECK (duplicate_strategy IS NULL OR duplicate_strategy IN ('skip','update')),
          validated_at timestamptz,
          imported_at timestamptz
        );

CREATE TABLE material_records (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          organization_id bigint NOT NULL REFERENCES organizations(id),
          original_code text NOT NULL,
          original_description text NOT NULL,
          normalized_description text,
          category text NOT NULL,
          subcategory text,
          manufacturer text,
          model text,
          part_number text,
          material_type text,
          uom text NOT NULL DEFAULT 'NOS',
          import_id bigint REFERENCES data_imports(id) ON DELETE SET NULL,
          processing_status text NOT NULL DEFAULT 'imported'
            CHECK (processing_status IN ('imported','normalised','classified','attributes_extracted','ready_for_matching','warning','error')),
          classification_confidence double precision
            CHECK (classification_confidence IS NULL OR classification_confidence BETWEEN 0 AND 100),
          classification_source text,
          quality_status text
            CHECK (quality_status IN ('good','warning','incomplete','invalid')),
          quality_checks text,
          is_active boolean NOT NULL DEFAULT true,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          source_row integer,
          UNIQUE (organization_id, original_code)
        );

CREATE TABLE material_attributes (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          material_id bigint NOT NULL REFERENCES material_records(id) ON DELETE CASCADE,
          attribute_name text NOT NULL CHECK (char_length(attribute_name) BETWEEN 2 AND 60),
          value text NOT NULL,
          normalized_value text,
          unit text,
          is_critical boolean NOT NULL DEFAULT false,
          extraction_method text NOT NULL DEFAULT 'imported'
            CHECK (extraction_method IN ('rule','manual','imported')),
          confidence double precision
            CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 100),
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          UNIQUE (material_id, attribute_name)
        );

-- ---------------------------------------------------------------------------
-- Matching
-- ---------------------------------------------------------------------------

-- evidence is jsonb: production SQL already performs JSON path queries against
-- it (json_extract on $.decision.state / band / reason). See README § JSON.
CREATE TABLE match_candidates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_material_id bigint NOT NULL REFERENCES material_records(id),
    candidate_material_id bigint NOT NULL REFERENCES material_records(id),
    semantic_score double precision NOT NULL DEFAULT 0 CHECK (semantic_score BETWEEN 0 AND 100),
    fuzzy_score double precision NOT NULL DEFAULT 0 CHECK (fuzzy_score BETWEEN 0 AND 100),
    technical_score double precision NOT NULL DEFAULT 0 CHECK (technical_score BETWEEN 0 AND 100),
    category_compatible boolean NOT NULL DEFAULT true,
    final_score double precision NOT NULL DEFAULT 0 CHECK (final_score BETWEEN 0 AND 100),
    match_type text NOT NULL DEFAULT 'needs_review'
      CHECK (match_type IN ('identical','near_duplicate','functional_equivalent','needs_review','different')),
    explanation text NOT NULL DEFAULT '',
    critical_difference text,
    status text NOT NULL DEFAULT 'pending'
      CHECK (status IN ('pending','approved','rejected','deferred')),
    evidence jsonb,
    match_run_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (source_material_id, candidate_material_id),
    CHECK (source_material_id <> candidate_material_id)
  );

CREATE TABLE match_decisions (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          match_id bigint NOT NULL REFERENCES match_candidates(id),
          decision text NOT NULL CHECK (decision IN ('approved','rejected','deferred','sent_for_review')),
          reviewer text NOT NULL,
          comment text,
          decided_at timestamptz NOT NULL DEFAULT now(),
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

CREATE TABLE review_queue (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          match_id bigint NOT NULL UNIQUE REFERENCES match_candidates(id),
          priority text NOT NULL DEFAULT 'medium' CHECK (priority IN ('high','medium','low')),
          reason text NOT NULL,
          critical_difference text,
          status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','resolved')),
          assigned_reviewer text,
          opened_at timestamptz NOT NULL DEFAULT now(),
          resolved_at timestamptz,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

-- ---------------------------------------------------------------------------
-- Harmonization
-- ---------------------------------------------------------------------------

CREATE TABLE common_materials (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          code text NOT NULL UNIQUE,
          name text NOT NULL,
          description text,
          category text NOT NULL,
          source_match_id bigint REFERENCES match_candidates(id),
          is_active boolean NOT NULL DEFAULT true,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

CREATE TABLE material_mappings (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          cmi_id bigint NOT NULL REFERENCES common_materials(id),
          material_id bigint NOT NULL UNIQUE REFERENCES material_records(id),
          organization_id bigint NOT NULL REFERENCES organizations(id),
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

-- ---------------------------------------------------------------------------
-- Governance: audit + evaluation
-- ---------------------------------------------------------------------------

CREATE TABLE audit_logs (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          action text NOT NULL CHECK (action IN (
            'material_created','material_updated','material_reprocessed','import_performed','match_generated',
            'proposal_created','proposal_approved','proposal_rejected','proposal_deferred',
            'mapping_created','common_material_created','user_login','user_login_failed','user_logout','user_created',
            'user_updated','user_role_changed','demo_role_switched',
            'import_created','import_started','import_failed','import_retried'
          )),
          entity_type text NOT NULL,
          entity_id bigint,
          actor text NOT NULL DEFAULT 'system',
          details text,
          created_at timestamptz NOT NULL DEFAULT now()
        );

CREATE TABLE evaluation_runs (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          run_id text NOT NULL UNIQUE,
          "timestamp" timestamptz NOT NULL,
          dataset text NOT NULL,
          dataset_version text NOT NULL,
          pairs integer NOT NULL CHECK (pairs >= 0),
          accuracy double precision NOT NULL,
          macro_precision double precision NOT NULL,
          macro_recall double precision NOT NULL,
          macro_f1 double precision NOT NULL,
          weighted_f1 double precision NOT NULL,
          confusion text NOT NULL,
          false_positives integer NOT NULL CHECK (false_positives >= 0),
          false_negatives integer NOT NULL CHECK (false_negatives >= 0),
          conflict_detected integer NOT NULL CHECK (conflict_detected >= 0),
          conflict_expected integer NOT NULL CHECK (conflict_expected >= 0),
          conflict_rate double precision NOT NULL,
          review_rate double precision NOT NULL,
          matcher_config text NOT NULL,
          build_id text NOT NULL,
          notes text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

-- ---------------------------------------------------------------------------
-- Auth (application-local users/sessions — see supabase/rls-design.md for the
-- relationship to Supabase auth.users at cutover time)
-- ---------------------------------------------------------------------------

CREATE TABLE users (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          name text NOT NULL CHECK (char_length(name) BETWEEN 2 AND 120),
          email text NOT NULL UNIQUE CHECK (char_length(email) BETWEEN 5 AND 200),
          password_hash text NOT NULL,
          role text NOT NULL CHECK (role IN ('cpse_material_manager','cpse_technical_reviewer','authority','platform_admin')),
          organization_id bigint REFERENCES organizations(id),
          status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive')),
          last_login_at timestamptz,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          CHECK (
            (role IN ('cpse_material_manager','cpse_technical_reviewer') AND organization_id IS NOT NULL)
            OR role IN ('authority','platform_admin')
          )
        );

CREATE TABLE sessions (
          id text PRIMARY KEY,
          user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          created_at timestamptz NOT NULL DEFAULT now(),
          expires_at timestamptz NOT NULL,
          created_via text NOT NULL DEFAULT 'login' CHECK (created_via IN ('login','demo_switch')),
          demo_of_user_id bigint REFERENCES users(id),
          CHECK (expires_at > created_at)
        );

-- ---------------------------------------------------------------------------
-- Step-4 job execution model: matching runs
-- ---------------------------------------------------------------------------

CREATE TABLE matching_runs (
          id text PRIMARY KEY,
          status text NOT NULL DEFAULT 'QUEUED'
            CHECK (status IN ('QUEUED','RUNNING','COMPLETED','FAILED')),
          total_candidates integer NOT NULL DEFAULT 0 CHECK (total_candidates >= 0),
          processed_candidates integer NOT NULL DEFAULT 0 CHECK (processed_candidates >= 0),
          successful_candidates integer NOT NULL DEFAULT 0 CHECK (successful_candidates >= 0),
          failed_candidates integer NOT NULL DEFAULT 0 CHECK (failed_candidates >= 0),
          chunk_size integer NOT NULL CHECK (chunk_size >= 1),
          started_at timestamptz,
          completed_at timestamptz,
          heartbeat_at timestamptz,
          error_message text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

CREATE TABLE matching_run_chunks (
          run_id text NOT NULL REFERENCES matching_runs(id),
          chunk_index integer NOT NULL CHECK (chunk_index >= 0),
          first_pair integer NOT NULL CHECK (first_pair >= 0),
          pair_count integer NOT NULL CHECK (pair_count >= 0),
          status text NOT NULL DEFAULT 'PENDING'
            CHECK (status IN ('PENDING','RUNNING','COMMITTED','FAILED')),
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (run_id, chunk_index)
        );

-- DB-authoritative single-active-run guard (same constant-expression partial
-- unique index idiom as SQLite; at most one QUEUED/RUNNING matching job).
CREATE UNIQUE INDEX uq_matching_runs_active
  ON matching_runs ((1))
  WHERE status IN ('QUEUED', 'RUNNING');

-- ---------------------------------------------------------------------------
-- Step-5 job execution model: import runs + staging
-- ---------------------------------------------------------------------------

CREATE TABLE import_runs (
          id text PRIMARY KEY,
          data_import_id bigint NOT NULL REFERENCES data_imports(id),
          status text NOT NULL DEFAULT 'QUEUED'
            CHECK (status IN ('QUEUED','RUNNING','COMPLETED','FAILED')),
          filename text NOT NULL,
          file_type text NOT NULL,
          total_rows integer NOT NULL DEFAULT 0 CHECK (total_rows >= 0),
          processed_rows integer NOT NULL DEFAULT 0 CHECK (processed_rows >= 0),
          successful_rows integer NOT NULL DEFAULT 0 CHECK (successful_rows >= 0),
          failed_rows integer NOT NULL DEFAULT 0 CHECK (failed_rows >= 0),
          chunk_size integer NOT NULL CHECK (chunk_size >= 1),
          started_at timestamptz,
          completed_at timestamptz,
          heartbeat_at timestamptz,
          error_message text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

CREATE TABLE import_run_chunks (
          run_id text NOT NULL REFERENCES import_runs(id),
          chunk_index integer NOT NULL CHECK (chunk_index >= 0),
          first_row integer NOT NULL CHECK (first_row >= 0),
          row_count integer NOT NULL CHECK (row_count >= 0),
          status text NOT NULL DEFAULT 'PENDING'
            CHECK (status IN ('PENDING','RUNNING','COMMITTED','FAILED')),
          error_message text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (run_id, chunk_index)
        );

-- Single-active-import guard.
CREATE UNIQUE INDEX uq_import_runs_active
  ON import_runs ((1))
  WHERE status IN ('QUEUED', 'RUNNING');

-- Staging: the bounded row snapshot each import job executes from.
CREATE TABLE import_rows (
          job_id text NOT NULL REFERENCES import_runs(id) ON DELETE CASCADE,
          row_number integer NOT NULL CHECK (row_number >= 1),
          severity text NOT NULL CHECK (severity IN ('VALID','WARNING','ERROR')),
          code text NOT NULL DEFAULT '',
          description text NOT NULL DEFAULT '',
          category text,
          manufacturer text,
          model text,
          part_number text,
          uom text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (job_id, row_number)
        );

-- ---------------------------------------------------------------------------
-- Application-owned migration registry (mirrors SQLite _migrations)
-- ---------------------------------------------------------------------------

CREATE TABLE _migrations (
    version integer PRIMARY KEY,
    name text NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT now()
  );

-- ---------------------------------------------------------------------------
-- Indexes — translated 1:1 from SQLite v11 (names preserved)
-- ---------------------------------------------------------------------------

-- organizations: code UNIQUE constraint covers lookup.

CREATE INDEX idx_imports_org ON data_imports(organization_id);
CREATE INDEX idx_imports_status ON data_imports(status);

CREATE INDEX idx_material_org ON material_records(organization_id);
CREATE INDEX idx_material_org_code ON material_records(organization_id, original_code);
CREATE INDEX idx_material_category ON material_records(category);
CREATE INDEX idx_material_import ON material_records(import_id);
CREATE INDEX idx_material_status ON material_records(processing_status);
CREATE INDEX idx_material_quality ON material_records(quality_status);
CREATE INDEX idx_material_source_row ON material_records(source_row);

CREATE INDEX idx_attributes_material ON material_attributes(material_id);
CREATE INDEX idx_attributes_name_value ON material_attributes(attribute_name, normalized_value);

CREATE INDEX idx_match_source ON match_candidates(source_material_id);
CREATE INDEX idx_match_candidate ON match_candidates(candidate_material_id);
CREATE INDEX idx_match_status ON match_candidates(status);
CREATE INDEX idx_match_status_score ON match_candidates(status, final_score);
CREATE INDEX idx_match_type ON match_candidates(match_type);
CREATE INDEX idx_match_run ON match_candidates(match_run_id);

CREATE INDEX idx_decisions_match ON match_decisions(match_id);

CREATE INDEX idx_queue_status_priority ON review_queue(status, priority);
CREATE INDEX idx_queue_opened ON review_queue(opened_at);

CREATE INDEX idx_mappings_cmi ON material_mappings(cmi_id);
CREATE INDEX idx_mappings_org ON material_mappings(organization_id);

CREATE INDEX idx_audit_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_audit_actor ON audit_logs(actor, created_at);

CREATE INDEX idx_eval_runs_time ON evaluation_runs("timestamp");

CREATE INDEX idx_users_org ON users(organization_id);
CREATE INDEX idx_users_role ON users(role);

CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_expiry ON sessions(expires_at);

CREATE INDEX idx_match_runs_status ON matching_runs(status);
CREATE INDEX idx_match_runs_heartbeat ON matching_runs(heartbeat_at);

CREATE INDEX idx_import_runs_status ON import_runs(status);
CREATE INDEX idx_import_runs_import ON import_runs(data_import_id);
CREATE INDEX idx_import_runs_heartbeat ON import_runs(heartbeat_at);

CREATE INDEX idx_import_rows_job ON import_rows(job_id);

-- ---------------------------------------------------------------------------
-- Step 12 - procurement data foundation (separate domain from matching).
-- Suppliers + procurement records; cmi_id is NULLABLE and must always be
-- validated against material_mappings by the service layer (material_mappings
-- remains the authoritative identity relationship - procurement never creates
-- or infers CMIs). unit_price/currency/quantity: numeric-safe TEXT+numeric
-- pairing (see column comments); UOM preserved verbatim, no conversion.
-- ---------------------------------------------------------------------------

CREATE TABLE suppliers (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          supplier_code text NOT NULL UNIQUE,
          supplier_name text NOT NULL,
          region text,
          is_active boolean NOT NULL DEFAULT true,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now()
        );

CREATE TABLE procurement_records (
          id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          organization_id bigint NOT NULL REFERENCES organizations(id),
          material_id bigint NOT NULL REFERENCES material_records(id),
          cmi_id bigint REFERENCES common_materials(id),
          supplier_id bigint NOT NULL REFERENCES suppliers(id),
          purchase_order_reference text NOT NULL,
          purchase_date text NOT NULL,
          delivery_date text,
          quantity numeric NOT NULL CHECK (quantity > 0),
          uom text NOT NULL CHECK (char_length(uom) BETWEEN 1 AND 12),
          unit_price numeric,
          currency text,
          plant_location text,
          procurement_status text NOT NULL
            CHECK (procurement_status IN ('ORDERED','PARTIALLY_DELIVERED','DELIVERED','CANCELLED')),
          source_system text,
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          CHECK (
            (unit_price IS NULL AND currency IS NULL)
            OR (unit_price IS NOT NULL AND currency IS NOT NULL)
          )
        );

CREATE INDEX idx_proc_org ON procurement_records(organization_id);
CREATE INDEX idx_proc_material ON procurement_records(material_id);
CREATE INDEX idx_proc_cmi ON procurement_records(cmi_id);
CREATE INDEX idx_proc_supplier ON procurement_records(supplier_id);
CREATE INDEX idx_proc_date ON procurement_records(purchase_date);
CREATE INDEX idx_proc_cmi_date ON procurement_records(cmi_id, purchase_date);
CREATE INDEX idx_proc_org_date ON procurement_records(organization_id, purchase_date);

-- Audit: extend the action CHECK with procurement lifecycle events.
ALTER TABLE audit_logs DROP CONSTRAINT audit_logs_action_check;
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_action_check CHECK (action IN (
  'material_created','material_updated','material_reprocessed','import_performed','match_generated',
  'proposal_created','proposal_approved','proposal_rejected','proposal_deferred',
  'mapping_created','common_material_created','user_login','user_login_failed','user_logout','user_created',
  'user_updated','user_role_changed','demo_role_switched',
  'import_created','import_started','import_failed','import_retried',
  'procurement_created','procurement_updated','supplier_created'
));

-- ---------------------------------------------------------------------------
-- Step 13 - procurement ingestion (reuses the generic import-job machinery).
-- import_runs.kind selects the executor; frozen rows default to 'materials'.
-- procurement_import_rows: typed staging (import_rows keeps its frozen shape).
-- uq_procurement_row_signature: deterministic re-import guard - a repeated
-- upload of the SAME purchase line is skipped; legitimate repeated purchases
-- (different PO/date/quantity) import normally.
-- ---------------------------------------------------------------------------

ALTER TABLE import_runs ADD COLUMN kind text NOT NULL DEFAULT 'materials'
  CHECK (kind IN ('materials','procurement'));

CREATE TABLE procurement_import_rows (
          job_id text NOT NULL REFERENCES import_runs(id) ON DELETE CASCADE,
          row_number integer NOT NULL CHECK (row_number >= 1),
          severity text NOT NULL CHECK (severity IN ('VALID','WARNING','ERROR')),
          org_code text NOT NULL DEFAULT '',
          material_code text NOT NULL DEFAULT '',
          cmi_code text,
          supplier_code text NOT NULL DEFAULT '',
          purchase_order_reference text NOT NULL DEFAULT '',
          purchase_date text NOT NULL DEFAULT '',
          delivery_date text,
          quantity text NOT NULL DEFAULT '',
          uom text NOT NULL DEFAULT '',
          unit_price text,
          currency text,
          plant_location text,
          status text,
          row_signature text NOT NULL DEFAULT '',
          created_at timestamptz NOT NULL DEFAULT now(),
          updated_at timestamptz NOT NULL DEFAULT now(),
          PRIMARY KEY (job_id, row_number)
        );

CREATE INDEX idx_proc_import_rows_job ON procurement_import_rows(job_id);

ALTER TABLE procurement_records ADD COLUMN row_signature text NOT NULL DEFAULT '';

CREATE UNIQUE INDEX IF NOT EXISTS uq_procurement_row_signature
  ON procurement_records(row_signature) WHERE row_signature <> '';

-- Audit: extend the action CHECK with the procurement import lifecycle.
ALTER TABLE audit_logs DROP CONSTRAINT audit_logs_action_check;
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_action_check CHECK (action IN (
  'material_created','material_updated','material_reprocessed','import_performed','match_generated',
  'proposal_created','proposal_approved','proposal_rejected','proposal_deferred',
  'mapping_created','common_material_created','user_login','user_login_failed','user_logout','user_created',
  'user_updated','user_role_changed','demo_role_switched',
  'import_created','import_started','import_failed','import_retried',
  'procurement_created','procurement_updated','supplier_created',
  'procurement_import_started','procurement_import_completed','procurement_import_failed'
));

-- Step 15 - procurement opportunity detection. Opportunities are PERSISTED
-- (section 40B): the table stores the governed human-review state plus an
-- explainable evidence summary - never a copy of procurement rows.
-- detection_key is UNIQUE and deterministic (type + identity scope + period),
-- so detection reruns upsert and never duplicate OPEN opportunities.
CREATE TABLE procurement_opportunities (
  id bigserial PRIMARY KEY,
  opportunity_type text NOT NULL CHECK (opportunity_type IN (
    'CROSS_CPSE_DEMAND','REPEATED_PROCUREMENT','FRAGMENTED_DEMAND',
    'UNHARMONIZED_RELATED_PROCUREMENT','MULTI_SUPPLIER_ACTIVITY',
    'HIGH_PROCUREMENT_ACTIVITY')),
  status text NOT NULL DEFAULT 'OPEN'
    CHECK (status IN ('OPEN','ACKNOWLEDGED','DISMISSED','RESOLVED')),
  detection_key text NOT NULL UNIQUE,
  cmi_id bigint REFERENCES common_materials(id),
  organization_id bigint REFERENCES organizations(id),
  supplier_id bigint REFERENCES suppliers(id),
  material_id bigint REFERENCES material_records(id),
  period_start date,
  period_end date,
  title text NOT NULL,
  description text NOT NULL,
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  priority_signal integer NOT NULL DEFAULT 0 CHECK (priority_signal >= 0),
  reviewed_by text,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (review_note IS NULL OR reviewed_by IS NOT NULL)
);

CREATE INDEX idx_opp_status ON procurement_opportunities(status);
CREATE INDEX idx_opp_type ON procurement_opportunities(opportunity_type);
CREATE INDEX idx_opp_cmi ON procurement_opportunities(cmi_id);
CREATE INDEX idx_opp_org ON procurement_opportunities(organization_id);
CREATE INDEX idx_opp_created ON procurement_opportunities(created_at);

-- Audit: extend the action CHECK with the opportunity review lifecycle
-- (detection itself is silent - only human transitions are audited).
ALTER TABLE audit_logs DROP CONSTRAINT audit_logs_action_check;
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_action_check CHECK (action IN (
  'material_created','material_updated','material_reprocessed','import_performed','match_generated',
  'proposal_created','proposal_approved','proposal_rejected','proposal_deferred',
  'mapping_created','common_material_created','user_login','user_login_failed','user_logout','user_created',
  'user_updated','user_role_changed','demo_role_switched',
  'import_created','import_started','import_failed','import_retried',
  'procurement_created','procurement_updated','supplier_created',
  'procurement_import_started','procurement_import_completed','procurement_import_failed',
  'procurement_opportunity_acknowledged','procurement_opportunity_dismissed',
  'procurement_opportunity_resolved','procurement_opportunity_reopened'
));

COMMIT;

-- ===========================================================================
-- Step 17 - controlled UOM conversion registry (SQLite migrate v16 parity).
-- Explicit directional master-data rules with INTEGER factors only: the
-- decimal-safe aggregation normalized_cents = qty_cents * factor stays pure
-- integer arithmetic. No reverse derivation; SET is deliberately UNCONVERTED.
-- DOMAIN_SPECIFIC is reserved (requires authoritative per-material data).
-- ===========================================================================
CREATE TABLE uom_conversion_rules (
  id bigserial PRIMARY KEY,
  from_uom text NOT NULL CHECK (btrim(from_uom) <> ''),
  to_uom text NOT NULL CHECK (btrim(to_uom) <> ''),
  factor integer NOT NULL CHECK (factor > 0),
  rule_type text NOT NULL CHECK (rule_type IN ('ALIAS','SCALE','DOMAIN_SPECIFIC')),
  source text NOT NULL DEFAULT 'SYSTEM_DEFINED' CHECK (btrim(source) <> ''),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (from_uom <> to_uom),
  UNIQUE (from_uom, to_uom, rule_type)
);

CREATE INDEX idx_uom_rules_from ON uom_conversion_rules(from_uom);
CREATE INDEX idx_uom_rules_active ON uom_conversion_rules(is_active, from_uom);

INSERT INTO uom_conversion_rules (from_uom, to_uom, factor, rule_type, source, description) VALUES
  ('PCS','EA', 1, 'ALIAS','SYSTEM_DEFINED','Count-unit alias: piece = each.'),
  ('NOS','EA', 1, 'ALIAS','SYSTEM_DEFINED','Count-unit alias: numbers = each.'),
  ('KG','G', 1000, 'SCALE','SYSTEM_DEFINED','SI mass scale: kilogram to gram.'),
  ('TON','G', 1000000, 'SCALE','SYSTEM_DEFINED','Mass scale: metric ton to gram (metric tonne only; short/hundredweight tons are ambiguous and stay UNCONVERTED - section 11). Direct hop to the canonical unit: no rule chains.'),
  ('L','ML', 1000, 'SCALE','SYSTEM_DEFINED','SI volume scale: litre to millilitre.'),
  ('M','MM', 1000, 'SCALE','SYSTEM_DEFINED','SI length scale: metre to millimetre.'),
  ('CM','MM', 10, 'SCALE','SYSTEM_DEFINED','SI length scale: centimetre to millimetre.');

-- No audit CHECK change in Step 17: the registry is read-only in this step
-- (rules are migration/seed-defined; rule administration is future work).

-- ===========================================================================
-- Step 18 - uom_domain_rules (migration v17): governed DOMAIN_SPECIFIC
-- (CMI-scoped) UOM rules. CREATE-only; the Step 17 uom_conversion_rules
-- registry and its 7 SYSTEM_DEFINED rows are untouched. Lifecycle:
-- PENDING -> APPROVED | REJECTED; APPROVED -> DISABLED -> APPROVED (re-enable).
-- Only APPROVED rows affect comparable quantities, and only for procurement
-- records of the scoped CMI's mapped members. The partial UNIQUE index
-- enforces at most one LIVE rule per (cmi_id, from_uom).
-- ===========================================================================
CREATE TABLE uom_domain_rules (
  id bigserial PRIMARY KEY,
  cmi_id integer NOT NULL REFERENCES common_materials(id),
  from_uom text NOT NULL CHECK (btrim(from_uom) <> ''),
  to_uom text NOT NULL CHECK (btrim(to_uom) <> ''),
  factor integer NOT NULL CHECK (factor > 0),
  rule_type text NOT NULL DEFAULT 'DOMAIN_SPECIFIC' CHECK (rule_type = 'DOMAIN_SPECIFIC'),
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED','DISABLED')),
  source text NOT NULL DEFAULT 'GOVERNED' CHECK (btrim(source) <> ''),
  reason text NOT NULL CHECK (btrim(reason) <> ''),
  created_by text NOT NULL,
  approved_by text,
  decided_at text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (from_uom <> to_uom)
);

CREATE INDEX idx_uom_domain_lookup ON uom_domain_rules(cmi_id, from_uom, status);
CREATE UNIQUE INDEX uq_uom_domain_live ON uom_domain_rules(cmi_id, from_uom)
  WHERE status IN ('PENDING','APPROVED','DISABLED');

-- Step 18 audit note: PostgreSQL audit_logs.action is unconstrained text, so
-- no CHECK migration is needed; the five governed UOM lifecycle events
-- (uom_rule_created/approved/rejected/disabled/re_enabled) insert directly.
-- (SQLite extends its CHECK via the migration-v17 audit_logs rebuild.)

-- ============================================================
-- v18 (Step 19): uom_rule_history - append-only governed rule history
-- ============================================================
CREATE TABLE IF NOT EXISTS uom_rule_history (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rule_id BIGINT NOT NULL REFERENCES uom_domain_rules(id),
  cmi_id BIGINT NOT NULL,
  from_uom TEXT NOT NULL,
  to_uom TEXT NOT NULL,
  factor INTEGER NOT NULL,
  rule_type TEXT NOT NULL DEFAULT 'DOMAIN_SPECIFIC' CHECK (rule_type = 'DOMAIN_SPECIFIC'),
  previous_status TEXT CHECK (previous_status IS NULL OR previous_status IN ('PENDING','APPROVED','REJECTED','DISABLED')),
  new_status TEXT NOT NULL CHECK (new_status IN ('PENDING','APPROVED','REJECTED','DISABLED')),
  action TEXT NOT NULL CHECK (action IN ('CREATE','APPROVE','REJECT','DISABLE','RE_ENABLE')),
  actor TEXT NOT NULL CHECK (btrim(actor) <> ''),
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_uom_rule_history_rule ON uom_rule_history(rule_id, id);
CREATE INDEX IF NOT EXISTS idx_uom_rule_history_time ON uom_rule_history(created_at);
CREATE INDEX IF NOT EXISTS idx_uom_rule_history_actor ON uom_rule_history(actor, created_at);
CREATE UNIQUE INDEX IF NOT EXISTS uq_uom_rule_history_create ON uom_rule_history(rule_id) WHERE action = 'CREATE';
-- Append-only enforcement on PostgreSQL: only INSERT is granted on this
-- table (UPDATE/DELETE are physically refused), mirroring the SQLite
-- trigger-based append-only contract in migration v18.
REVOKE UPDATE, DELETE ON uom_rule_history FROM PUBLIC;

-- ============================================================
-- v19 (Step 20): uom_domain_rule_versions - immutable content versions,
-- amendment workflow, versioned history, uom_rule_amended audit action
-- ============================================================
CREATE TABLE IF NOT EXISTS uom_domain_rule_versions (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rule_id BIGINT NOT NULL REFERENCES uom_domain_rules(id),
  version_number INTEGER NOT NULL CHECK (version_number >= 1),
  cmi_id BIGINT NOT NULL,
  from_uom TEXT NOT NULL CHECK (btrim(from_uom) <> ''),
  to_uom TEXT NOT NULL CHECK (btrim(to_uom) <> ''),
  factor INTEGER NOT NULL CHECK (factor > 0),
  rule_type TEXT NOT NULL DEFAULT 'DOMAIN_SPECIFIC' CHECK (rule_type = 'DOMAIN_SPECIFIC'),
  amendment_reason TEXT,
  created_by TEXT NOT NULL CHECK (btrim(created_by) <> ''),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  supersedes_version_id BIGINT,
  CHECK (from_uom <> to_uom),
  UNIQUE (rule_id, version_number)
);
CREATE INDEX IF NOT EXISTS idx_uom_rule_versions_rule ON uom_domain_rule_versions(rule_id, version_number);
CREATE INDEX IF NOT EXISTS idx_uom_rule_versions_supersedes ON uom_domain_rule_versions(supersedes_version_id);
-- Immutable on PostgreSQL: INSERT-only (mirrors the SQLite trigger-based
-- immutability of migration v19).
REVOKE UPDATE, DELETE ON uom_domain_rule_versions FROM PUBLIC;
-- Live-rule version pointers (additive). Deliberately plain BIGINT, no FK:
-- a REFERENCES here would create a FK cycle with
-- uom_domain_rule_versions.rule_id, which is illegal for the migration/backup
-- tool's topological ordering. The rule_id FK keeps the parent-child edge;
-- the pointers are written only inside governed transactions.
--   ALTER TABLE uom_domain_rules
--     ADD COLUMN effective_version_id BIGINT,
--     ADD COLUMN pending_version_id BIGINT;
--   CREATE INDEX idx_uom_domain_pending ON uom_domain_rules(pending_version_id);
-- History gains version_id / previous_version_id / action 'AMEND' (existing
-- rows are preserved verbatim with NULL version context - history is never
-- rewritten, even by migrations). audit_logs CHECK gains 'uom_rule_amended'
-- via the established rebuild pattern. Backfill: exactly one v1 version per
-- existing rule; APPROVED/DISABLED rules get effective_version_id = v1
-- (DISABLED rules were approved before being disabled and convert again on
-- re-enable); PENDING/REJECTED rules keep NULL (never had an effective
-- version). Content of v1 = live rule content, so conversion behavior is
-- unchanged.
